# SPDX-License-Identifier: GPL-2.0

dtb-$(CONFIG_ARCH_MXC) += \
			  imx8mm-icore-ctouch2.dtb \
			  imx8mm-icore-starterkit.dtb \
			  imx8mp-icore-2e-net-phy.dtb \
			  imx8mp-icore-2e-ctouch2.dtb \
			  imx8mp-icore-2e-starterkit.dtb \
			  imx8mp-icore-ctouch2.dtb \
			  imx8mp-icore-fasteth-ctouch2.dtb \
			  imx8mp-icore-fasteth-starterkit.dtb \
			  imx8mp-icore-starterkit.dtb \
			  imx8mp-smarcore-xtouch2.dtb \
			  imx8qxp-icore-starterkit.dtb \
			  imx8qxp-icore-ctouch2.dtb \
			  imx8ulp-microgea-microdev-rev3.dtb \
			  imx93-icore-ctouch2.dtb \
			  imx93-icore-starterkit.dtb \
			  imx93-icore-ctouch31.dtb \
			  imx93-icore-ctouch31-amp10.dtb \
			  imx93-microgea-evb.dtb \
			  imx93-microgea-micro5.dtb \
			  imx91-microgea-starterkit.dtb \
			  imx91-microgea-microdev2.dtb \
			  imx91-microgea-microdev3.dtb \
			  imx91-microgea-micro5.dtb \
			  imx91-microgea-evb.dtb \
			  imx95-icore-starterkit.dtb \
			  imx95-icore-ctouch31-amp10.dtb \
			  imx95-smarcore-multimedia-4k.dtb \
			  imx95-smarcore-xtouch2.dtb 
